### ISSUE TITLE
Environment Configuration 

### ISSUE THREAD

**Issue by engahmed1190** [txzhao/rl-zoo#1]
Hello @txzhao 

I would like to thank you for this code it is very good!

I am confused in the part related to the size of `N_ACTIONS` , `N_STATES` , `ENV_A_SHAPE`

```
N_ACTIONS = env.action_space.n
N_STATES = env.observation_space.shape[0]
ENV_A_SHAPE = 0 if isinstance(env.action_space.sample(), int) else env.action_space.sample().shape     # to confirm the shape
env_config = {'n_actions': N_ACTIONS, 'n_states': N_STATES, 'env_a_shape': ENV_A_SHAPE}
```

in my case, I have used a custom environment where action in 3 numbers array size 3*1 . can you please clarify what is the difference  between N_ACTIONS and ENV_A_SHAPE

Thanks

**Comment by txzhao** [comment]
N_ACTIONS denotes the number of actions you may choose, which in your case should be 3.

ENV_A_SHAPE is used to confirm that the actions take the form of a single integer instead of an array or other form. For instance, in CartPole-v0, agent could only go left (0) or right (1), which means ENV_A_SHAPE equals to 0. 

If your action space consists of several options and each of them take the form of an array, (e.g. a robot arm with two joints can take one of the actions [0, 0], [0, 1], [1, 0], [1,1], where 1 means adding effort to the current joint), then ENV_A_SHAPE will be the size of action taken instead of size of action space (for the above example, ENV_A_SHAPE = 2, N_ACTIONS = 4).

**Comment by engahmed1190** [comment]
Hi @txzhao 

Thanks for your respond .

in my case, I have action space of 3 values so ENV_A_SHAPE is 3 but the N_ACTION is very big where I have 3 values each of them can take value from 0 to 1000.
ENV_A_SHAPE i found it have to be tuple as the reshape take tuple to reshape 
what do suggest in this case.
values i am using now 

N_STATES = 25 
N_ACTIONS = 729 
ENV_A_SHAPE = (1, 3)

I have edited the else part to be as following what do you suggest in the Greedy case


```
def choose_action(self, x, EPSILON):
		x = Variable(torch.unsqueeze(torch.FloatTensor(x), 0))
		# input only one sample
		if np.random.uniform() > EPSILON:   # greedy
			actions_value = self.eval_net.forward(x)
			action = torch.max(actions_value, 1)[1].data.numpy()
			print (actions_value  , action)
			action = action[0] if self.env_a_shape == 0 else action.reshape(self.env_a_shape)  	# return the argmax index
		else:   # random
			action = np.random.randint(1000, size =self.env_a_shape)
			print (action)		
			action = action if self.env_a_shape == 0 else action.reshape(self.env_a_shape)
		return action
```
